"""empty message

Revision ID: 17fec3529891
Revises: 626362df9d58
Create Date: 2022-09-12 15:28:09.691544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fec3529891'
down_revision = '626362df9d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created', sa.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
