"""empty message

Revision ID: 2dec5cef2a84
Revises: b217dfe7b273
Create Date: 2022-09-02 12:11:08.531589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dec5cef2a84'
down_revision = 'b217dfe7b273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_firstname', sa.String(length=150), nullable=True),
    sa.Column('employer_lastname', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employer_firstname', sa.VARCHAR(length=150), nullable=True),
    sa.Column('employer_lastname', sa.VARCHAR(length=150), nullable=True),
    sa.Column('description', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employer')
    # ### end Alembic commands ###
