"""empty message

Revision ID: 4effceecc28f
Revises: 17fec3529891
Create Date: 2022-09-20 12:10:43.274398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4effceecc28f'
down_revision = '17fec3529891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employer_firstname', sa.VARCHAR(length=150), nullable=True),
    sa.Column('employer_lastname', sa.VARCHAR(length=150), nullable=True),
    sa.Column('description', sa.VARCHAR(length=10000), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
