"""empty message

Revision ID: b217dfe7b273
Revises: 3803f794c37e
Create Date: 2022-09-01 13:24:04.453531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b217dfe7b273'
down_revision = '3803f794c37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_firstname', sa.String(length=150), nullable=True),
    sa.Column('employer_lastname', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employers')
    # ### end Alembic commands ###
